#!/usr/bin/env bash
# install-fishlike-zsh.sh — network install of a fish-like zsh (latest).
#
# Philosophy:
#   - Pull current share/ + plugins + Antidote + fzf from the network
#   - No commit pins, no SHA packaging, no frozen “release set”
#   - Install writes files once; shell startup only sources them
#   - Does not dirty unrelated state; uninstall moves managed trees to backup
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/kongjiadongyuan/zish/main/install-fishlike-zsh.sh | bash
#   bash install-fishlike-zsh.sh --uninstall
#
# Local overrides: ${ZDOTDIR:-$HOME}/.zshrc.local

set -euo pipefail

INSTALLER_VERSION="3.0.1"
MIN_ZSH_VERSION="5.4.2"
ZISH_REPO="${ZISH_REPO:-kongjiadongyuan/zish}"
ZISH_REF="${ZISH_REF:-main}"
SHARE_BASE="${ZISH_SHARE_BASE:-https://raw.githubusercontent.com/${ZISH_REPO}/${ZISH_REF}/share}"
ANTIDOTE_REPO="${ANTIDOTE_REPO:-https://github.com/mattmc3/antidote.git}"
ANTIDOTE_BRANCH="${ANTIDOTE_BRANCH:-main}"
FZF_REPO_API="${FZF_REPO_API:-https://api.github.com/repos/junegunn/fzf/releases/latest}"

FLAG_CHSH=0
FLAG_NO_CHSH=0
FLAG_FORCE=0
FLAG_DRY_RUN=0
FLAG_INSTALL_DEPS=0
FLAG_NON_INTERACTIVE=0
FLAG_UNINSTALL=0

HOME="${HOME:-$(cd ~ && pwd)}"
ZDOTDIR="${ZDOTDIR:-$HOME}"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"

FISHLIKE_CONFIG_DIR="${FISHLIKE_CONFIG_DIR:-$XDG_CONFIG_HOME/fishlike-zsh}"
FISHLIKE_ENV="${FISHLIKE_CONFIG_DIR}/env.zsh"
FISHLIKE_CONFIG="${FISHLIKE_CONFIG_DIR}/config.zsh"
ZSH_PLUGINS_TXT="${FISHLIKE_CONFIG_DIR}/plugins.txt"
ZSH_PLUGINS_ZSH="${FISHLIKE_CONFIG_DIR}/plugins.zsh"
ZSHRC="${ZDOTDIR}/.zshrc"
LOCAL_RC="${ZDOTDIR}/.zshrc.local"

FISHLIKE_DATA_DIR="${FISHLIKE_DATA_DIR:-$XDG_DATA_HOME/fishlike-zsh}"
FISHLIKE_BACKUP_DIR="${FISHLIKE_BACKUP_DIR:-$FISHLIKE_DATA_DIR/backup}"
FISHLIKE_STATE_FILE="${FISHLIKE_STATE_FILE:-$FISHLIKE_DATA_DIR/state}"
ANTIDOTE_DIR="${FISHLIKE_ANTIDOTE_DIR:-$FISHLIKE_DATA_DIR/antidote}"
ANTIDOTE_CACHE_DIR="${FISHLIKE_ANTIDOTE_HOME:-$XDG_CACHE_HOME/fishlike-zsh/plugins}"
LOCAL_BIN="${FISHLIKE_BIN_DIR:-$FISHLIKE_DATA_DIR/bin}"

TIMESTAMP="$(date +%Y%m%d%H%M%S)"
MANAGED_MARKER="# Managed by install-fishlike-zsh.sh; edits may be replaced."
BUNDLE_MARKER="# Generated by install-fishlike-zsh.sh; do not edit."
LOADER_START="# >>> fishlike-zsh loader (install-fishlike-zsh.sh) >>>"
LOADER_END="# <<< fishlike-zsh loader (install-fishlike-zsh.sh) <<<"
LEGACY_START="# >>> fishlike-zsh managed (install-fishlike-zsh.sh) >>>"
LEGACY_END="# <<< fishlike-zsh managed (install-fishlike-zsh.sh) <<<"

TEMP_PATHS=()

if [[ -t 1 ]]; then
  C_RESET=$'\033[0m' C_BOLD=$'\033[1m' C_DIM=$'\033[2m'
  C_GREEN=$'\033[32m' C_YELLOW=$'\033[33m' C_RED=$'\033[31m' C_CYAN=$'\033[36m'
else
  C_RESET= C_BOLD= C_DIM= C_GREEN= C_YELLOW= C_RED= C_CYAN=
fi

log()  { printf '%s==>%s %s\n' "$C_BOLD$C_CYAN" "$C_RESET" "$*"; }
ok()   { printf '%s[ok]%s %s\n' "$C_GREEN" "$C_RESET" "$*"; }
warn() { printf '%s[warn]%s %s\n' "$C_YELLOW" "$C_RESET" "$*" >&2; }
err()  { printf '%s[err]%s %s\n' "$C_RED" "$C_RESET" "$*" >&2; }
die()  { err "$*"; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }

can_prompt() {
  (( ! FLAG_NON_INTERACTIVE )) || return 1
  [[ -c /dev/tty ]] || return 1
  [[ -t 0 || -t 1 || -t 2 ]]
}

ask_yes_no() {
  local question="$1" default="$2" answer suffix
  case "$default" in
    yes) suffix='[Y/n]' ;;
    no) suffix='[y/N]' ;;
    *) die "invalid prompt default: $default" ;;
  esac
  if ! can_prompt; then
    [[ "$default" == yes ]]
    return
  fi
  while true; do
    printf '%s %s ' "$question" "$suffix" >/dev/tty
    if ! IFS= read -r answer </dev/tty; then
      [[ "$default" == yes ]]
      return
    fi
    case "$answer" in
      '') [[ "$default" == yes ]]; return ;;
      y|Y|yes|YES|Yes) return 0 ;;
      n|N|no|NO|No) return 1 ;;
      *) printf 'Please answer y or n.\n' >/dev/tty ;;
    esac
  done
}

register_temp() { TEMP_PATHS+=("$1"); }
cleanup_temp_paths() {
  local path
  set +u
  for path in "${TEMP_PATHS[@]}"; do
    [[ -n "$path" ]] && rm -rf -- "$path" 2>/dev/null || true
  done
  set -u
}
trap cleanup_temp_paths EXIT

run() {
  if (( FLAG_DRY_RUN )); then
    printf '%s[dry-run]%s' "$C_DIM" "$C_RESET"
    printf ' %q' "$@"
    printf '\n'
    return 0
  fi
  "$@"
}

usage() {
  cat <<EOF
Usage: bash install-fishlike-zsh.sh [options]

Installs the latest fishlike-zsh bits from the network (${ZISH_REF}).

Options:
  --chsh / --no-chsh   Login-shell question
  --force              Approve replacements / uninstall without prompts
  --dry-run            Preview only
  --install-deps       Try package manager for missing zsh/git/curl
  --uninstall          Remove loader + managed trees (moved to backup/)
  --non-interactive    Never prompt; use defaults
  -h, --help           This help

Environment:
  ZDOTDIR  FISHLIKE_CONFIG_DIR  FISHLIKE_DATA_DIR
  FISHLIKE_SHARE_DIR  ZISH_REF  ZISH_REPO
EOF
  exit 0
}

parse_args() {
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --chsh) FLAG_CHSH=1 ;;
      --no-chsh) FLAG_NO_CHSH=1 ;;
      --force) FLAG_FORCE=1 ;;
      --dry-run) FLAG_DRY_RUN=1 ;;
      --install-deps) FLAG_INSTALL_DEPS=1 ;;
      --uninstall) FLAG_UNINSTALL=1 ;;
      --non-interactive) FLAG_NON_INTERACTIVE=1 ;;
      -h|--help) usage ;;
      *) die "unknown flag: $1 (try --help)" ;;
    esac
    shift
  done
  if (( FLAG_CHSH && FLAG_NO_CHSH )); then
    die "use only one of --chsh / --no-chsh"
  fi
}

abs_ok() {
  [[ -n "$1" && "$1" == /* && "$1" != *$'\n'* ]]
}

validate_paths() {
  abs_ok "$HOME" || die "HOME must be absolute"
  abs_ok "$ZDOTDIR" || die "ZDOTDIR must be absolute"
  abs_ok "$FISHLIKE_CONFIG_DIR" || die "FISHLIKE_CONFIG_DIR must be absolute"
  abs_ok "$FISHLIKE_DATA_DIR" || die "FISHLIKE_DATA_DIR must be absolute"
  case "$FISHLIKE_CONFIG_DIR" in /|"$HOME"|"$ZDOTDIR") die "unsafe FISHLIKE_CONFIG_DIR" ;; esac
  case "$FISHLIKE_DATA_DIR" in /|"$HOME"|"$ZDOTDIR"|"$FISHLIKE_CONFIG_DIR") die "unsafe FISHLIKE_DATA_DIR" ;; esac
}

# ---- backups ----------------------------------------------------------------
next_backup_path() {
  local source="$1" safe candidate suffix=0
  safe="$(printf '%s' "${source#/}" | tr '/' '_')"
  [[ -n "$safe" ]] || safe="path"
  candidate="$FISHLIKE_BACKUP_DIR/$TIMESTAMP/$safe"
  while [[ -e "$candidate" || -L "$candidate" ]]; do
    suffix=$((suffix + 1))
    candidate="$FISHLIKE_BACKUP_DIR/$TIMESTAMP/${safe}.${suffix}"
  done
  printf '%s\n' "$candidate"
}

backup_file() {
  local source="$1" backup
  [[ -e "$source" || -L "$source" ]] || return 0
  backup="$(next_backup_path "$source")"
  log "backup $source -> $backup"
  (( FLAG_DRY_RUN )) && return 0
  mkdir -p "$(dirname "$backup")"
  cp -a "$source" "$backup"
}

move_to_backup() {
  local source="$1" backup
  [[ -e "$source" || -L "$source" ]] || return 0
  backup="$(next_backup_path "$source")"
  log "move $source -> $backup"
  (( FLAG_DRY_RUN )) && return 0
  mkdir -p "$(dirname "$backup")"
  mv "$source" "$backup"
}

is_fishlike_owned_path() {
  case "$1" in
    */fishlike-zsh|*/fishlike-zsh/*) return 0 ;;
    *) return 1 ;;
  esac
}

require_replace() {
  local path="$1"
  (( FLAG_FORCE )) && return 0
  warn "conflicting path: $path"
  if ask_yes_no "Back up and replace conflicting managed paths?" no; then
    FLAG_FORCE=1
    return 0
  fi
  die "replacement declined: $path"
}

atomic_write() {
  local dest="$1" content="$2" parent tmp
  parent="$(dirname "$dest")"
  mkdir -p "$parent"
  tmp="$(mktemp "$parent/.fishlike-write.XXXXXX")"
  register_temp "$tmp"
  printf '%s' "$content" >"$tmp" || die "write failed: $dest"
  chmod 0600 "$tmp"
  mv -f "$tmp" "$dest" || die "replace failed: $dest"
}

write_if_changed() {
  local dest="$1" content="$2"
  if [[ -f "$dest" ]] && cmp -s "$dest" <(printf '%s' "$content"); then
    ok "unchanged $dest"
    return 0
  fi
  if [[ -L "$dest" ]]; then die "refusing symlink: $dest"; fi
  if [[ -e "$dest" && ! -f "$dest" ]]; then die "refusing non-file: $dest"; fi
  if [[ -f "$dest" ]]; then
    if ! grep -Fqx "$MANAGED_MARKER" "$dest" 2>/dev/null && \
       ! { IFS= read -r _first <"$dest" && [[ "$_first" == "$BUNDLE_MARKER" ]]; }; then
      require_replace "$dest"
    fi
    backup_file "$dest"
  fi
  if (( FLAG_DRY_RUN )); then
    log "would write $dest"
    return 0
  fi
  atomic_write "$dest" "$content"
  ok "wrote $dest"
}

# ---- deps -------------------------------------------------------------------
zsh_ok() {
  have zsh || return 1
  MIN_ZSH_VERSION="$MIN_ZSH_VERSION" zsh -fc \
    'autoload -Uz is-at-least && is-at-least "$MIN_ZSH_VERSION" "$ZSH_VERSION"' \
    >/dev/null 2>&1
}

ensure_deps() {
  local need_zsh=0 need_git=0 need_dl=0
  zsh_ok || need_zsh=1
  have git || need_git=1
  have curl || have wget || need_dl=1

  if (( need_zsh == 0 && need_git == 0 && need_dl == 0 )); then
    ok "system dependencies present"
    return 0
  fi

  if (( ! FLAG_INSTALL_DEPS )); then
    warn "missing: $(
      (( need_zsh )) && printf 'zsh '
      (( need_git )) && printf 'git '
      (( need_dl )) && printf 'curl/wget '
    )"
    warn "install them, or re-run with --install-deps"
    (( FLAG_DRY_RUN )) && return 0
  fi

  if (( FLAG_INSTALL_DEPS )) && ! (( FLAG_DRY_RUN )); then
    if have brew; then
      local b=()
      (( need_zsh )) && b+=(zsh)
      (( need_git )) && b+=(git)
      (( need_dl )) && b+=(curl)
      ((${#b[@]})) && brew install "${b[@]}"
    elif have apt-get && { [[ "$(id -u)" -eq 0 ]] || have sudo; }; then
      local a=() s=()
      (( need_zsh )) && a+=(zsh)
      (( need_git )) && a+=(git)
      (( need_dl )) && a+=(curl ca-certificates)
      if [[ "$(id -u)" -eq 0 ]]; then s=(); else s=(sudo); fi
      if ((${#a[@]})); then
        "${s[@]}" env DEBIAN_FRONTEND=noninteractive apt-get update -qq
        "${s[@]}" env DEBIAN_FRONTEND=noninteractive apt-get install -y "${a[@]}"
      fi
    else
      die "cannot auto-install deps on this system"
    fi
  fi

  (( FLAG_DRY_RUN )) && return 0
  hash -r 2>/dev/null || true
  zsh_ok || die "zsh ${MIN_ZSH_VERSION}+ required"
  have git || die "git required"
  have curl || have wget || die "curl or wget required"
}

download() {
  local url="$1" dest="$2"
  if have curl; then
    curl -fsSL --proto '=https' --tlsv1.2 --connect-timeout 15 --retry 3 -o "$dest" "$url"
  else
    wget -q -O "$dest" "$url"
  fi
}

# ---- share payload (latest from network, or local checkout) -----------------
resolve_share() {
  local dir src
  if [[ -n "${FISHLIKE_SHARE_DIR:-}" && -f "$FISHLIKE_SHARE_DIR/config.zsh" && -f "$FISHLIKE_SHARE_DIR/plugins.txt" ]]; then
    SHARE_CONFIG_SRC="$FISHLIKE_SHARE_DIR/config.zsh"
    SHARE_PLUGINS_SRC="$FISHLIKE_SHARE_DIR/plugins.txt"
    ok "using FISHLIKE_SHARE_DIR"
    return 0
  fi
  src="${BASH_SOURCE[0]:-}"
  if [[ -n "$src" && -f "$src" ]]; then
    dir="$(cd "$(dirname "$src")" && pwd)/share"
    if [[ -f "$dir/config.zsh" && -f "$dir/plugins.txt" ]]; then
      SHARE_CONFIG_SRC="$dir/config.zsh"
      SHARE_PLUGINS_SRC="$dir/plugins.txt"
      ok "using local share/: $dir"
      return 0
    fi
  fi

  log "fetching latest share/ from $SHARE_BASE"
  if (( FLAG_DRY_RUN )); then
    SHARE_CONFIG_SRC=""
    SHARE_PLUGINS_SRC=""
    return 0
  fi
  local tmp
  tmp="$(mktemp -d "${TMPDIR:-/tmp}/fishlike-share.XXXXXX")"
  register_temp "$tmp"
  download "$SHARE_BASE/config.zsh" "$tmp/config.zsh"
  download "$SHARE_BASE/plugins.txt" "$tmp/plugins.txt"
  SHARE_CONFIG_SRC="$tmp/config.zsh"
  SHARE_PLUGINS_SRC="$tmp/plugins.txt"
  ok "share payload downloaded"
}

install_share_files() {
  log "installing configuration"
  if (( FLAG_DRY_RUN )) && [[ -z "${SHARE_CONFIG_SRC:-}" ]]; then
    log "would write config + plugins.txt from network"
    return 0
  fi
  local cfg plugs
  cfg="$(cat "$SHARE_CONFIG_SRC"; printf '\034')"; cfg="${cfg%$'\034'}"
  plugs="$(cat "$SHARE_PLUGINS_SRC"; printf '\034')"; plugs="${plugs%$'\034'}"
  [[ "$cfg" == "$MANAGED_MARKER"* ]] || cfg="$MANAGED_MARKER"$'\n'"$cfg"
  [[ "$plugs" == "$MANAGED_MARKER"* ]] || plugs="$MANAGED_MARKER"$'\n'"$plugs"
  write_if_changed "$FISHLIKE_CONFIG" "$cfg"
  write_if_changed "$ZSH_PLUGINS_TXT" "$plugs"

  local env
  env="$(
    printf '%s\n' "$MANAGED_MARKER"
    printf '# fishlike-zsh env v%s\n' "$INSTALLER_VERSION"
    printf 'typeset -g FISHLIKE_ANTIDOTE_DIR=%q\n' "$ANTIDOTE_DIR"
    printf 'typeset -g FISHLIKE_ANTIDOTE_HOME=%q\n' "$ANTIDOTE_CACHE_DIR"
    printf 'typeset -g FISHLIKE_PLUGIN_FILE=%q\n' "$ZSH_PLUGINS_TXT"
    printf 'typeset -g FISHLIKE_PLUGIN_BUNDLE=%q\n' "$ZSH_PLUGINS_ZSH"
    printf 'typeset -g FISHLIKE_LOCAL_BIN=%q\n' "$LOCAL_BIN"
    printf 'typeset -g FISHLIKE_LOCAL_RC=%q\n' "$LOCAL_RC"
  )"
  write_if_changed "$FISHLIKE_ENV" "$env"
}

# ---- fzf latest -------------------------------------------------------------
install_fzf() {
  if [[ -x "$LOCAL_BIN/fzf" ]]; then
    ok "fzf present: $LOCAL_BIN/fzf ($("$LOCAL_BIN/fzf" --version 2>/dev/null | head -1))"
    export PATH="$LOCAL_BIN:$PATH"
    return 0
  fi

  log "installing latest fzf to $LOCAL_BIN"
  if (( FLAG_DRY_RUN )); then
    log "would download latest fzf release"
    return 0
  fi

  local os arch tag asset url tmp json
  os="$(uname -s | tr '[:upper:]' '[:lower:]')"
  arch="$(uname -m)"
  case "$arch" in
    x86_64|amd64) arch=amd64 ;;
    aarch64|arm64) arch=arm64 ;;
    armv7l) arch=armv7 ;;
    *) die "unsupported arch: $arch" ;;
  esac
  case "$os" in linux|darwin) ;; *) die "unsupported OS: $os" ;; esac

  json="$(mktemp "${TMPDIR:-/tmp}/fzf-rel.XXXXXX")"
  register_temp "$json"
  download "$FZF_REPO_API" "$json"
  tag="$(sed -n 's/.*"tag_name"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$json" | head -1)"
  [[ -n "$tag" ]] || die "could not parse fzf latest tag"
  asset="fzf-${tag#v}-${os}_${arch}.tar.gz"
  url="https://github.com/junegunn/fzf/releases/download/${tag}/${asset}"

  tmp="$(mktemp -d "${TMPDIR:-/tmp}/fzf.XXXXXX")"
  register_temp "$tmp"
  download "$url" "$tmp/$asset"
  have tar || die "tar required"
  tar -xzf "$tmp/$asset" -C "$tmp" fzf
  mkdir -p "$LOCAL_BIN"
  chmod 0755 "$tmp/fzf"
  mv -f "$tmp/fzf" "$LOCAL_BIN/fzf"
  export PATH="$LOCAL_BIN:$PATH"
  ok "fzf ${tag} -> $LOCAL_BIN/fzf"
}

# ---- antidote latest + plugin bundle ----------------------------------------
install_antidote() {
  log "installing Antidote (${ANTIDOTE_BRANCH})"
  if (( FLAG_DRY_RUN )); then
    log "would clone/update $ANTIDOTE_REPO"
    return 0
  fi
  mkdir -p "$(dirname "$ANTIDOTE_DIR")"
  if [[ -d "$ANTIDOTE_DIR/.git" ]]; then
    git -C "$ANTIDOTE_DIR" fetch -q origin "$ANTIDOTE_BRANCH"
    git -C "$ANTIDOTE_DIR" checkout -q "$ANTIDOTE_BRANCH"
    git -C "$ANTIDOTE_DIR" pull -q --ff-only origin "$ANTIDOTE_BRANCH" || \
      git -C "$ANTIDOTE_DIR" reset -q --hard "origin/$ANTIDOTE_BRANCH"
  else
    [[ -e "$ANTIDOTE_DIR" ]] && require_replace "$ANTIDOTE_DIR" && move_to_backup "$ANTIDOTE_DIR"
    git clone -q --depth 1 --branch "$ANTIDOTE_BRANCH" "$ANTIDOTE_REPO" "$ANTIDOTE_DIR"
  fi
  [[ -r "$ANTIDOTE_DIR/antidote.zsh" ]] || die "antidote.zsh missing"
  ok "Antidote at $(git -C "$ANTIDOTE_DIR" rev-parse --short HEAD)"
}

build_plugins() {
  log "building plugin bundle (latest from network)"
  if (( FLAG_DRY_RUN )); then
    log "would antidote bundle -> $ZSH_PLUGINS_ZSH"
    return 0
  fi
  [[ -r "$ZSH_PLUGINS_TXT" ]] || die "missing $ZSH_PLUGINS_TXT"
  mkdir -p "$ANTIDOTE_CACHE_DIR" "$(dirname "$ZSH_PLUGINS_ZSH")"

  local tmp err
  tmp="$(mktemp "$ZSH_PLUGINS_ZSH.tmp.XXXXXX")"
  err="$(mktemp "${TMPDIR:-/tmp}/fishlike-bundle.XXXXXX")"
  register_temp "$tmp"
  register_temp "$err"

  # Refresh clones to latest each install.
  if [[ -d "$ANTIDOTE_CACHE_DIR/github.com" ]]; then
    find "$ANTIDOTE_CACHE_DIR/github.com" -mindepth 2 -maxdepth 2 -type d -name .git -print0 2>/dev/null \
      | while IFS= read -r -d '' g; do
          git -C "$(dirname "$g")" pull -q --ff-only 2>/dev/null || true
        done
  fi

  if ! env ANTIDOTE_HOME="$ANTIDOTE_CACHE_DIR" \
      FISHLIKE_ANTIDOTE_DIR="$ANTIDOTE_DIR" \
      FISHLIKE_PLUGIN_FILE="$ZSH_PLUGINS_TXT" \
      FISHLIKE_BUNDLE_MARKER="$BUNDLE_MARKER" \
      zsh -fc '
        emulate zsh
        setopt EXTENDED_GLOB
        typeset -g ANTIDOTE_HOME="$ANTIDOTE_HOME"
        source "$FISHLIKE_ANTIDOTE_DIR/antidote.zsh" || exit 1
        zstyle ":antidote:bundle" path-style full
        zstyle -d ":antidote:bundle" use-friendly-names 2>/dev/null || true
        print -r -- "$FISHLIKE_BUNDLE_MARKER"
        antidote bundle <"$FISHLIKE_PLUGIN_FILE"
      ' >"$tmp" 2>"$err"; then
    warn "antidote bundle failed:"
    tail -n 40 "$err" >&2 || true
    die "could not build plugin bundle"
  fi
  grep -qE '^source ' "$tmp" || die "bundle has no source lines"
  chmod 0600 "$tmp"
  mv -f "$tmp" "$ZSH_PLUGINS_ZSH"
  ok "plugin bundle ready"
}

# ---- zshrc loader -----------------------------------------------------------
loader_count() {
  local f="$1" a b
  a="$(grep -Fxc "$LOADER_START" "$f" 2>/dev/null || true)"
  b="$(grep -Fxc "$LEGACY_START" "$f" 2>/dev/null || true)"
  printf '%s\n' "$((a + b))"
}

is_start() { [[ "$1" == "$LOADER_START" || "$1" == "$LEGACY_START" ]]; }
is_end()   { [[ "$1" == "$LOADER_END" || "$1" == "$LEGACY_END" ]]; }

render_loader() {
  local env_q config_q
  printf -v env_q '%q' "$FISHLIKE_ENV"
  printf -v config_q '%q' "$FISHLIKE_CONFIG"
  printf '%s\n' "$LOADER_START"
  printf 'if [[ -r %s ]]; then\n' "$env_q"
  printf '  source %s\n' "$env_q"
  printf '  [[ -r %s ]] && source %s\n' "$config_q" "$config_q"
  printf 'fi\n'
  printf '%s\n' "$LOADER_END"
}

update_zshrc() {
  local loader output='' line in_block=0 found=0 starts existing
  loader="$(render_loader; printf '\034')"; loader="${loader%$'\034'}"

  if [[ -L "$ZSHRC" ]]; then die "refusing symlinked .zshrc: $ZSHRC"; fi
  if [[ -e "$ZSHRC" && ! -f "$ZSHRC" ]]; then die ".zshrc not a file: $ZSHRC"; fi

  if [[ ! -f "$ZSHRC" ]]; then
    (( FLAG_DRY_RUN )) && { log "would create $ZSHRC"; return 0; }
    atomic_write "$ZSHRC" "$loader"
    ok "created $ZSHRC"
    return 0
  fi

  starts="$(loader_count "$ZSHRC")"
  (( starts <= 1 )) || die "duplicate fishlike blocks in $ZSHRC"

  if (( starts == 0 )); then
    existing="$(cat "$ZSHRC"; printf '\034')"; existing="${existing%$'\034'}"
    output="$existing"
    [[ -n "$output" && "$output" != *$'\n' ]] && output+=$'\n'
    [[ -n "$output" ]] && output+=$'\n'
    output+="$loader"
  else
    while IFS= read -r line || [[ -n "$line" ]]; do
      if is_start "$line"; then
        in_block=1; found=1; output+="$loader"
      elif is_end "$line"; then
        in_block=0
      elif (( ! in_block )); then
        output+="$line"$'\n'
      fi
    done <"$ZSHRC"
    (( found )) || die "incomplete fishlike block in $ZSHRC"
  fi

  if cmp -s "$ZSHRC" <(printf '%s' "$output"); then
    ok "unchanged loader in $ZSHRC"
    return 0
  fi
  backup_file "$ZSHRC"
  if (( FLAG_DRY_RUN )); then log "would update loader in $ZSHRC"; return 0; fi
  atomic_write "$ZSHRC" "$output"
  ok "updated loader in $ZSHRC"
}

remove_zshrc_loader() {
  [[ -f "$ZSHRC" ]] || return 0
  local starts output='' line in_block=0 found=0
  starts="$(loader_count "$ZSHRC")"
  (( starts == 0 )) && { ok "no loader in $ZSHRC"; return 0; }
  (( starts == 1 )) || die "malformed loader in $ZSHRC"
  while IFS= read -r line || [[ -n "$line" ]]; do
    if is_start "$line"; then in_block=1; found=1
    elif is_end "$line"; then in_block=0
    elif (( ! in_block )); then output+="$line"$'\n'
    fi
  done <"$ZSHRC"
  backup_file "$ZSHRC"
  if (( FLAG_DRY_RUN )); then log "would remove loader"; return 0; fi
  atomic_write "$ZSHRC" "$output"
  ok "removed loader from $ZSHRC"
}

# ---- state / uninstall ------------------------------------------------------
write_state() {
  (( FLAG_DRY_RUN )) && { log "would write state"; return 0; }
  mkdir -p "$(dirname "$FISHLIKE_STATE_FILE")"
  cat >"$FISHLIKE_STATE_FILE" <<EOF
# fishlike-zsh state v${INSTALLER_VERSION}
version=${INSTALLER_VERSION}
installed_at=${TIMESTAMP}
ref=${ZISH_REF}
config_dir=${FISHLIKE_CONFIG_DIR}
data_dir=${FISHLIKE_DATA_DIR}
backup_dir=${FISHLIKE_BACKUP_DIR}
plugin_cache=${ANTIDOTE_CACHE_DIR}
zshrc=${ZSHRC}
EOF
  chmod 0600 "$FISHLIKE_STATE_FILE"
  ok "wrote state $FISHLIKE_STATE_FILE"
}

uninstall_fishlike() {
  printf '%s\n' "${C_BOLD}fishlike-zsh uninstall v${INSTALLER_VERSION}${C_RESET}"
  printf '  target: %s\n\n' "$HOME"
  local -a victims=() p
  for p in "$FISHLIKE_CONFIG_DIR" "$ANTIDOTE_CACHE_DIR" "$ANTIDOTE_DIR" "$LOCAL_BIN" "$FISHLIKE_STATE_FILE"; do
    if [[ -e "$p" || -L "$p" ]] && is_fishlike_owned_path "$p"; then
      victims+=("$p")
    elif [[ "$p" == "$FISHLIKE_STATE_FILE" && -e "$p" ]]; then
      victims+=("$p")
    fi
  done
  printf 'Will strip loader from %s\n' "$ZSHRC"
  printf 'Will move into %s/%s/:\n' "$FISHLIKE_BACKUP_DIR" "$TIMESTAMP"
  ((${#victims[@]})) && printf '  %s\n' "${victims[@]}" || printf '  (nothing)\n'
  printf '\nWill NOT touch: %s, history, login shell, system packages\n\n' "$LOCAL_RC"
  if (( ! FLAG_FORCE )) && ! ask_yes_no "Proceed with uninstall?" no; then
    die "uninstall declined"
  fi
  remove_zshrc_loader
  for p in "${victims[@]}"; do move_to_backup "$p"; done
  ok "uninstall complete (backups: $FISHLIKE_BACKUP_DIR/$TIMESTAMP)"
}

maybe_chsh() {
  (( FLAG_NO_CHSH )) && { ok "login shell unchanged"; return 0; }
  local zsh_path current
  zsh_path="$(command -v zsh)"
  current="${SHELL:-}"
  [[ "$current" == "$zsh_path" ]] && { ok "login shell already zsh"; return 0; }
  if (( ! FLAG_CHSH )); then
    ask_yes_no "Set Zsh as your login shell?" no || { ok "login shell unchanged"; return 0; }
  fi
  have chsh || { warn "chsh unavailable"; return 0; }
  if (( FLAG_DRY_RUN )); then log "would chsh -s $zsh_path"; return 0; fi
  chsh -s "$zsh_path" || warn "chsh failed"
}

main() {
  parse_args "$@"
  validate_paths

  if (( FLAG_UNINSTALL )); then
    uninstall_fishlike
    return 0
  fi

  printf '%s\n' "${C_BOLD}fishlike-zsh installer v${INSTALLER_VERSION}${C_RESET}"
  printf '  target: %s  (latest from network: %s@%s)\n' "$HOME" "$ZISH_REPO" "$ZISH_REF"
  (( FLAG_DRY_RUN )) && printf '  mode: dry-run\n'
  printf '\n'

  ensure_deps
  resolve_share
  install_fzf
  install_antidote
  install_share_files
  build_plugins
  update_zshrc
  write_state
  maybe_chsh

  echo
  ok "done. Open a new terminal, or: exec zsh -l"
  printf '  config:    %s\n' "$FISHLIKE_CONFIG_DIR"
  printf '  backups:   %s\n' "$FISHLIKE_BACKUP_DIR"
  printf '  local:     %s\n' "$LOCAL_RC"
  printf '  uninstall: bash install-fishlike-zsh.sh --uninstall\n'
}

main "$@"
